import { Notice, TFile, Vault, normalizePath, requestUrl, App } from "obsidian";
import type { Monster } from "index";
import OpenAI from "openai";

/**
 * OpenAI Image Generator Service
 * Generates creature images using DALL-E API
 */

export interface ImageGenerationOptions {
    apiKey: string;
    style: string;
    saveFolder: string;
}

export class OpenAIImageGenerator {
    private static async ensureFolder(
        vault: Vault,
        folderPath: string
    ): Promise<string> {
        const normalizedFolder = normalizePath(folderPath);
        const folderExists = await vault.adapter.exists(normalizedFolder);
        if (!folderExists) {
            await vault.adapter.mkdir(normalizedFolder);
        }
        return normalizedFolder;
    }

    /**
     * Generate a DALL-E prompt from monster data
     */
    static generatePromptFromMonster(monster: Partial<Monster>, style: string): string {
        const parts: string[] = [];

        // Base description
        if (monster.name) {
            parts.push(`A creature named ${monster.name}`);
        }

        // Size and type
        const sizeType: string[] = [];
        if (monster.size) sizeType.push(monster.size.toLowerCase());
        if (monster.type) sizeType.push(monster.type.toLowerCase());
        if (sizeType.length > 0) {
            parts.push(sizeType.join(" "));
        }

        // Alignment for character flavor
        if (monster.alignment && monster.alignment !== "unaligned") {
            const alignmentDescriptors: Record<string, string> = {
                "lawful good": "noble and virtuous",
                "neutral good": "kind and benevolent",
                "chaotic good": "free-spirited and heroic",
                "lawful neutral": "orderly and disciplined",
                "neutral": "balanced",
                "chaotic neutral": "unpredictable and wild",
                "lawful evil": "tyrannical and cruel",
                "neutral evil": "malicious and selfish",
                "chaotic evil": "destructive and malevolent"
            };
            const descriptor = alignmentDescriptors[monster.alignment.toLowerCase()];
            if (descriptor) {
                parts.push(`with a ${descriptor} demeanor`);
            }
        }

        // Prioritize explicit appearance property
        if (monster.appearance) {
            parts.push(monster.appearance);
        } else {
            // Fallback: Add description if available
            if (monster.description) {
                parts.push(monster.description);
            }

            // Fallback: Extract appearance from traits
            if (monster.traits && Array.isArray(monster.traits)) {
                const appearanceTraits = monster.traits
                    .filter((t) =>
                        t.name?.toLowerCase().includes("appearance") ||
                        t.desc?.toLowerCase().includes("looks like") ||
                        t.desc?.toLowerCase().includes("appears as")
                    )
                    .map((t) => t.desc)
                    .slice(0, 2); // Limit to avoid token overflow

                if (appearanceTraits.length > 0) {
                    parts.push(appearanceTraits.join(". "));
                }
            }
        }

        // Build final prompt
        let prompt = parts.join(", ");

        // Add style instruction and explicit no-text directive
        prompt += `. ${style} style, high quality, detailed, fantasy RPG creature portrait, dramatic lighting. NO text, letters, words, or labels should appear in the image`;

        // Ensure prompt isn't too long (DALL-E has limits)
        if (prompt.length > 1000) {
            prompt = prompt.substring(0, 997) + "...";
        }

        return prompt;
    }

    /**
     * Generate an image using OpenAI DALL-E
     */
    static async generateImage(
        prompt: string,
        apiKey: string
    ): Promise<string> {
        if (!apiKey || apiKey.trim() === "") {
            throw new Error("OpenAI API key is not configured. Please add it in Fantasy Statblocks settings.");
        }

        try {
            const openai = new OpenAI({
                apiKey: apiKey,
                dangerouslyAllowBrowser: true // Required for client-side usage in Obsidian
            });

            const response = await openai.images.generate({
                model: "dall-e-3",
                prompt: prompt,
                n: 1,
                size: "1024x1024",
                quality: "standard",
            });

            if (!response.data || response.data.length === 0) {
                throw new Error("No image was generated by OpenAI");
            }

            const imageUrl = response.data[0].url;
            if (!imageUrl) {
                throw new Error("No image URL returned from OpenAI");
            }

            return imageUrl;
        } catch (error: any) {
            if (error.status === 401) {
                throw new Error("Invalid OpenAI API key. Please check your settings.");
            } else if (error.status === 429) {
                throw new Error("OpenAI API rate limit exceeded. Please try again later.");
            } else if (error.status === 400) {
                throw new Error("Invalid request to OpenAI. The prompt may contain prohibited content.");
            } else {
                throw new Error(`OpenAI API error: ${error.message || "Unknown error"}`);
            }
        }
    }

    /**
     * Download image from URL and save to vault
     */
    static async saveImageToVault(
        imageUrl: string,
        vault: Vault,
        folderPath: string,
        monsterName: string
    ): Promise<string> {
        try {
            // Ensure folder exists
            const normalizedFolder = await this.ensureFolder(
                vault,
                folderPath
            );

            // Download image using Obsidian's requestUrl to bypass CORS
            const response = await requestUrl({
                url: imageUrl,
                method: "GET"
            });

            if (response.status !== 200) {
                throw new Error(`Failed to download image: ${response.status}`);
            }

            // Get the array buffer from the response
            const arrayBuffer = response.arrayBuffer;

            // Generate filename
            const safeName = monsterName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
            const filename = `${safeName}.png`;
            const filePath = normalizePath(`${normalizedFolder}/${filename}`);

            // Save to vault
            await vault.adapter.writeBinary(filePath, arrayBuffer);

            return filePath;
        } catch (error: any) {
            throw new Error(`Failed to save image to vault: ${error.message}`);
        }
    }

    static async saveImageBytesToVault(
        imageData: ArrayBuffer | Uint8Array,
        vault: Vault,
        folderPath: string,
        monsterName: string
    ): Promise<string> {
        try {
            const normalizedFolder = await this.ensureFolder(vault, folderPath);

            const safeName = monsterName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
            const filename = `${safeName}.png`;
            const filePath = normalizePath(`${normalizedFolder}/${filename}`);

            const buffer =
                imageData instanceof ArrayBuffer
                    ? imageData
                    : imageData.buffer.slice(
                          imageData.byteOffset,
                          imageData.byteOffset + imageData.byteLength
                      );

            await vault.adapter.writeBinary(filePath, buffer);

            return filePath;
        } catch (error: any) {
            throw new Error(`Failed to save image to vault: ${error.message}`);
        }
    }

    /**
     * Update the image property in a creature's frontmatter
     */
    static async updateCreatureFrontmatter(
        app: App,
        filePath: string,
        imagePath: string
    ): Promise<boolean> {
        try {
            // Get the file
            const file = app.vault.getAbstractFileByPath(filePath);

            if (!file || !(file instanceof TFile)) {
                console.warn(`File not found for frontmatter update: ${filePath}`);
                return false;
            }

            // Update frontmatter using Obsidian's API
            await app.fileManager.processFrontMatter(file, (frontmatter) => {
                frontmatter.image = imagePath;
            });

            return true;
        } catch (error: any) {
            console.error("Failed to update frontmatter:", error);
            return false;
        }
    }

    /**
     * Main function to generate and save monster image
     */
    static async generateMonsterImage(
        monster: Partial<Monster>,
        vault: Vault,
        options: ImageGenerationOptions
    ): Promise<string> {
        const loadingNotice = new Notice("Generating AI image...", 0);

        try {
            // Generate prompt
            const prompt = this.generatePromptFromMonster(monster, options.style);
            console.log("Generated DALL-E prompt:", prompt);

            // Generate image
            loadingNotice.setMessage("Requesting image from OpenAI...");
            const imageUrl = await this.generateImage(prompt, options.apiKey);

            // Save to vault
            loadingNotice.setMessage("Saving image to vault...");
            const vaultPath = await this.saveImageToVault(
                imageUrl,
                vault,
                options.saveFolder,
                monster.name || "creature"
            );

            loadingNotice.hide();
            new Notice(`AI image generated successfully! Saved to ${vaultPath}`);

            return vaultPath;
        } catch (error: any) {
            loadingNotice.hide();
            const errorMessage = error.message || "Unknown error occurred";
            new Notice(`Failed to generate image: ${errorMessage}`, 10000);
            throw error;
        }
    }

    /**
     * Compress and prepare an image for OpenAI DALL-E 2 upload
     * - Crops to square (center crop) as required by DALL-E 2
     * - Prioritizes quality compression over resizing to preserve detail
     * - Compresses to be under maxSizeBytes by reducing quality first, then dimensions if needed
     * - Converts to RGBA PNG format
     */
    private static async compressAndPrepareImage(
        file: File,
        maxSizeBytes: number = 4 * 1024 * 1024, // 4MB
        maxDimension: number = 2048 // Keep larger size for better quality
    ): Promise<File> {
        return new Promise((resolve, reject) => {
            const img = new Image();
            const url = URL.createObjectURL(file);

            img.onload = async () => {
                try {
                    // Calculate initial square crop size (don't exceed maxDimension)
                    const cropSize = Math.min(img.width, img.height);
                    let currentDimension = Math.min(cropSize, maxDimension);
                    let compressedFile: File | null = null;

                    // Strategy 1: Try quality compression first at full(ish) resolution
                    console.log(`Starting compression with ${currentDimension}x${currentDimension}...`);

                    // Try different quality levels: 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60
                    for (let quality = 0.95; quality >= 0.60 && !compressedFile; quality -= 0.05) {
                        const processedFile = await this.resizeAndCropToSquare(
                            img,
                            currentDimension,
                            file.name,
                            quality
                        );

                        if (processedFile.size <= maxSizeBytes) {
                            compressedFile = processedFile;
                            console.log(
                                `Image compressed to ${processedFile.size} bytes at ${currentDimension}x${currentDimension}, quality ${quality.toFixed(2)}`
                            );
                        }
                    }

                    // Strategy 2: If quality compression failed, reduce dimensions
                    if (!compressedFile) {
                        console.log('Quality compression insufficient, reducing dimensions...');
                        currentDimension = Math.floor(currentDimension * 0.75); // Start at 75% of max

                        while (currentDimension >= 512 && !compressedFile) {
                            // Try quality levels again at this smaller size
                            for (let quality = 0.92; quality >= 0.60 && !compressedFile; quality -= 0.08) {
                                const processedFile = await this.resizeAndCropToSquare(
                                    img,
                                    currentDimension,
                                    file.name,
                                    quality
                                );

                                if (processedFile.size <= maxSizeBytes) {
                                    compressedFile = processedFile;
                                    console.log(
                                        `Image compressed to ${processedFile.size} bytes at ${currentDimension}x${currentDimension}, quality ${quality.toFixed(2)}`
                                    );
                                }
                            }

                            if (!compressedFile) {
                                currentDimension = Math.floor(currentDimension * 0.75);
                            }
                        }
                    }

                    URL.revokeObjectURL(url);

                    if (!compressedFile) {
                        reject(
                            new Error(
                                'Unable to compress image below 4MB size limit. Please try a smaller image.'
                            )
                        );
                        return;
                    }

                    resolve(compressedFile);
                } catch (error) {
                    URL.revokeObjectURL(url);
                    reject(error);
                }
            };

            img.onerror = () => {
                URL.revokeObjectURL(url);
                reject(new Error('Failed to load image file'));
            };

            img.src = url;
        });
    }

    /**
     * Resize image and crop to square with RGBA format and quality compression
     * Used by compressAndPrepareImage
     *
     * Uses a two-step process for quality compression:
     * 1. Convert to JPEG with quality parameter (lossy compression)
     * 2. Convert JPEG to PNG for RGBA support (required by OpenAI)
     */
    private static async resizeAndCropToSquare(
        img: HTMLImageElement,
        targetDimension: number,
        originalFileName: string,
        quality: number = 0.92
    ): Promise<File> {
        return new Promise(async (resolve, reject) => {
            try {
                // Calculate the size of the square crop from the original image
                // We'll take a square from the center of the image
                const cropSize = Math.min(img.width, img.height);

                // Calculate crop position (center crop)
                const sourceX = (img.width - cropSize) / 2;
                const sourceY = (img.height - cropSize) / 2;

                // Create canvas for the final square image
                const canvas = document.createElement('canvas');
                canvas.width = targetDimension;
                canvas.height = targetDimension;

                const ctx = canvas.getContext('2d');
                if (!ctx) {
                    reject(new Error('Failed to get canvas context'));
                    return;
                }

                // Draw the cropped and resized image
                // This takes a square crop from the center of the source image
                // and scales it to fill the target dimensions
                ctx.drawImage(
                    img,
                    sourceX,
                    sourceY,
                    cropSize,
                    cropSize, // source crop (square from center)
                    0,
                    0,
                    targetDimension,
                    targetDimension // destination (scaled to target)
                );

                // Step 1: Convert to JPEG with quality compression
                const jpegBlob = await new Promise<Blob>((resolveBlob, rejectBlob) => {
                    canvas.toBlob(
                        (blob) => {
                            if (!blob) {
                                rejectBlob(new Error('Failed to create JPEG blob'));
                                return;
                            }
                            resolveBlob(blob);
                        },
                        'image/jpeg',
                        quality
                    );
                });

                // Step 2: Load the compressed JPEG and convert to PNG for RGBA support
                const jpegUrl = URL.createObjectURL(jpegBlob);
                const compressedImg = new Image();

                compressedImg.onload = () => {
                    // Create new canvas for PNG conversion
                    const pngCanvas = document.createElement('canvas');
                    pngCanvas.width = targetDimension;
                    pngCanvas.height = targetDimension;

                    const pngCtx = pngCanvas.getContext('2d');
                    if (!pngCtx) {
                        URL.revokeObjectURL(jpegUrl);
                        reject(new Error('Failed to get PNG canvas context'));
                        return;
                    }

                    // Draw the compressed JPEG onto the PNG canvas
                    pngCtx.drawImage(compressedImg, 0, 0);

                    // Convert to PNG blob (supports RGBA)
                    pngCanvas.toBlob(
                        (pngBlob) => {
                            URL.revokeObjectURL(jpegUrl);

                            if (!pngBlob) {
                                reject(new Error('Failed to create PNG blob'));
                                return;
                            }

                            const file = new File(
                                [pngBlob],
                                originalFileName.replace(/\.[^.]+$/, '.png'),
                                { type: 'image/png' }
                            );
                            resolve(file);
                        },
                        'image/png'
                    );
                };

                compressedImg.onerror = () => {
                    URL.revokeObjectURL(jpegUrl);
                    reject(new Error('Failed to load compressed JPEG'));
                };

                compressedImg.src = jpegUrl;
            } catch (error) {
                reject(error);
            }
        });
    }

    /**
     * Convert an image file to RGBA PNG format
     * Required for OpenAI DALL-E 2 image editing API
     * @deprecated Use compressAndPrepareImage instead for better file size handling
     */
    private static async convertImageToRGBA(file: File): Promise<File> {
        return new Promise((resolve, reject) => {
            // Create an image element to load the file
            const img = new Image();
            const url = URL.createObjectURL(file);

            img.onload = () => {
                try {
                    // Create a canvas to redraw the image with RGBA
                    const canvas = document.createElement('canvas');
                    canvas.width = img.width;
                    canvas.height = img.height;

                    const ctx = canvas.getContext('2d');
                    if (!ctx) {
                        throw new Error('Failed to get canvas context');
                    }

                    // Draw the image (this automatically adds an alpha channel)
                    ctx.drawImage(img, 0, 0);

                    // Convert canvas to blob in PNG format (which supports RGBA)
                    canvas.toBlob((blob) => {
                        URL.revokeObjectURL(url);

                        if (!blob) {
                            reject(new Error('Failed to convert image to RGBA format'));
                            return;
                        }

                        // Create a new File from the blob
                        const rgbaFile = new File(
                            [blob],
                            file.name.replace(/\.[^.]+$/, '.png'),
                            { type: 'image/png' }
                        );

                        resolve(rgbaFile);
                    }, 'image/png');
                } catch (error) {
                    URL.revokeObjectURL(url);
                    reject(error);
                }
            };

            img.onerror = () => {
                URL.revokeObjectURL(url);
                reject(new Error('Failed to load image file'));
            };

            img.src = url;
        });
    }

    /**
     * Generate a fully transparent mask for DALL-E 2 image editing
     * The mask tells DALL-E which areas to regenerate (transparent = regenerate entire image)
     */
    private static async generateFullTransparentMask(file: File): Promise<File> {
        return new Promise((resolve, reject) => {
            // Load the image to get dimensions
            const img = new Image();
            const url = URL.createObjectURL(file);

            img.onload = () => {
                try {
                    // Create a canvas with same dimensions
                    const canvas = document.createElement('canvas');
                    canvas.width = img.width;
                    canvas.height = img.height;

                    const ctx = canvas.getContext('2d');
                    if (!ctx) {
                        throw new Error('Failed to get canvas context');
                    }

                    // Create fully transparent image (alpha = 0 everywhere)
                    // By default, canvas is transparent, so we don't need to draw anything
                    // Just export it as PNG

                    canvas.toBlob((blob) => {
                        URL.revokeObjectURL(url);

                        if (!blob) {
                            reject(new Error('Failed to create transparent mask'));
                            return;
                        }

                        // Create a File from the blob
                        const maskFile = new File(
                            [blob],
                            'mask.png',
                            { type: 'image/png' }
                        );

                        resolve(maskFile);
                    }, 'image/png');
                } catch (error) {
                    URL.revokeObjectURL(url);
                    reject(error);
                }
            };

            img.onerror = () => {
                URL.revokeObjectURL(url);
                reject(new Error('Failed to load image file for mask generation'));
            };

            img.src = url;
        });
    }

    static async generateMonsterImageFromPhoto(
        monster: Partial<Monster>,
        vault: Vault,
        photo: File,
        options: ImageGenerationOptions
    ): Promise<string> {
        if (!photo) {
            throw new Error("No source photo was provided.");
        }

        if (!options.apiKey || options.apiKey.trim() === "") {
            throw new Error(
                "OpenAI API key is not configured. Please add it in Fantasy Statblocks settings."
            );
        }

        const loadingNotice = new Notice("Enhancing photo with AI...", 0);

        try {
            // Compress and prepare image (resize to 1024x1024, crop to square, ensure under 4MB)
            loadingNotice.setMessage("Compressing and preparing image...");
            const preparedPhoto = await this.compressAndPrepareImage(photo);

            // Generate fully transparent mask (tells DALL-E to transform entire image)
            // Use the prepared photo so mask dimensions match
            loadingNotice.setMessage("Generating transformation mask...");
            const mask = await this.generateFullTransparentMask(preparedPhoto);

            const openai = new OpenAI({
                apiKey: options.apiKey,
                dangerouslyAllowBrowser: true
            });

            const prompt = `${this.generatePromptFromMonster(
                monster,
                options.style
            )} Transform the provided miniature photograph into a lifelike fantasy creature portrait while keeping the pose and recognizable gear.`;

            loadingNotice.setMessage("Uploading photo to OpenAI...");
            const response = await openai.images.edit({
                model: "dall-e-2",
                prompt,
                image: preparedPhoto,
                mask: mask,
                size: "1024x1024"
            });

            if (!response.data || response.data.length === 0) {
                throw new Error("No image was generated by OpenAI");
            }

            const imageData = response.data[0];
            let vaultPath: string;

            loadingNotice.setMessage("Saving image to vault...");

            if (imageData.url) {
                vaultPath = await this.saveImageToVault(
                    imageData.url,
                    vault,
                    options.saveFolder,
                    monster.name || "creature"
                );
            } else if (imageData.b64_json) {
                const byteCharacters = atob(imageData.b64_json);
                const byteNumbers = new Array(byteCharacters.length);
                for (let i = 0; i < byteCharacters.length; i++) {
                    byteNumbers[i] = byteCharacters.charCodeAt(i);
                }
                const byteArray = new Uint8Array(byteNumbers);
                vaultPath = await this.saveImageBytesToVault(
                    byteArray,
                    vault,
                    options.saveFolder,
                    monster.name || "creature"
                );
            } else {
                throw new Error("OpenAI did not return usable image data.");
            }

            loadingNotice.hide();
            new Notice(`AI image generated successfully! Saved to ${vaultPath}`);

            return vaultPath;
        } catch (error: any) {
            loadingNotice.hide();
            const errorMessage = error.message || "Unknown error occurred";
            new Notice(`Failed to generate image: ${errorMessage}`, 10000);
            throw error;
        }
    }
}
